name: Java CI Telematix Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup build
        uses: gradle/gradle-build-action@v2

      - name: Execute gradle assemble
        run: ./gradlew assemble

  test:
    needs: checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup gradle for tests
        uses: gradle/gradle-build-action@v2

      - name: Execute gradle test
        run: ./gradlew test

  checkstyle:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup gradle for checkstyle
        uses: gradle/gradle-build-action@v2

      - name: Execute gradle checkstyleMain
        run: ./gradlew checkstyleMain --stacktrace

      - name: Execute gradle checkstyleTest
        run: ./gradlew checkstyleTest --stacktrace
